[project]
name = "spotify-nano-challenge-tic-ia"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Yan Santos", email = "yansantosrodrigues.dev@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "joblib>=1.6.0",
    "librosa>=1.0.0",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "python-multipart>=0.0.32",
    "soundfile>=0.14.0",
    "uvicorn>=0.52.4",
]

[project.scripts]
spotify-nano-challenge-tic-ia = "spotify_nano_challenge_tic_ia:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
